name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - run: npm install
      - run: npm run build
      
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}