name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Next.js
        run: npm run build
      
      - name: Deploy to Hostinger
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}